version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "17:00"
      timezone: America/New_York
    open-pull-requests-limit: 10
    groups:
      devvit:
        patterns:
          - devvit
          - "@devvit/*"
      eslint:
        patterns:
          - eslint
          - "@eslint/*"
          - typescript-eslint
      vite:
        patterns:
          - vite
          - "@vitejs/*"
      tailwind:
        patterns:
          - tailwindcss
          - "@tailwindcss/*"
      react:
        patterns:
          - react
          - react-dom
          - "@types/react"
          - "@types/react-dom"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "17:00"
      timezone: America/New_York
